apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vopuwd9ct-nodejs 
  janus-idp.io/tekton: vopuwd9ct-nodejs
  backstage.io/kubernetes-id: vopuwd9ct-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vopuwd9ct-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  